---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kebechet-administrator
spec:
  templates:
    - name: kebechet-administrator
      resubmitPendingPods: true
      inputs:
        parameters:
          - name: "THOTH_PACKAGE_NAME"
          - name: "THOTH_PACKAGE_VERSION"
          - name: "THOTH_PACKAGE_INDEX"
          - name: "THOTH_SOLVER_NAME"
          - name: "THOTH_MESSAGE_TYPE"
      outputs:
        artifacts:
          - name: messagestobesentdocument
            path: "/mnt/workdir/messages_to_be_sent.json"
      container:
        name: kebechet-administrator
        image: workflow-helpers
        env:
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                key: deployment-name
                name: thoth
          - name: THOTH_WORKFLOW_TASK
            value: "kebechet_administrator"
          - name: APP_SCRIPT
            value: "app.sh"
          - name: THOTH_PACKAGE_NAME
            value: "{{inputs.parameters.THOTH_PACKAGE_NAME}}"
          - name: THOTH_PACKAGE_VERSION
            value: "{{inputs.parameters.THOTH_PACKAGE_VERSION}}"
          - name: THOTH_PACKAGE_INDEX
            value: "{{inputs.parameters.THOTH_PACKAGE_INDEX}}"
          - name: THOTH_SOLVER_NAME
            value: "{{inputs.parameters.THOTH_SOLVER_NAME}}"
          - name: THOTH_MESSAGE_TYPE
            value: "{{inputs.parameters.THOTH_MESSAGE_TYPE}}"
          - name: KNOWLEDGE_GRAPH_HOST
            valueFrom:
              configMapKeyRef:
                key: postgresql-host
                name: thoth
          - name: KNOWLEDGE_GRAPH_PORT
            value: "5432"
          - name: KNOWLEDGE_GRAPH_SSL_DISABLED
            value: "1"
          - name: KNOWLEDGE_GRAPH_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-user
          - name: KNOWLEDGE_GRAPH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-password
          - name: KNOWLEDGE_GRAPH_DATABASE
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-name
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workdir
